# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Vadim Macagon
subtitle: '/(software (developer|engineer))|programmer/' 
description: A blog about programming.
author: Vadim Macagon
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vadim.macagon.com
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - CNAME

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true
## disable default highlighter so that the Code Mirror one can be used instead
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
code_mirror:
  enable: true
  theme: default
  line_number: true

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: true
    breaks: false
    linkify: false
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 1
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: 'v'           
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: true
    # Class used for the permalink anchor tag.
    permalinkClass: heading-anchor 
    # The symbol used to make the permalink, when using the default anchor renderer this should
    # be a character or plain text. However, when font_awesome_icons is enabled it will hijack
    # the default renderer and will expect the permalinkSymbol to match a FontAwesome icon id
    # (in font_awesome_icons.yml). 
    permalinkSymbol: 'anchor'

# Category & Tag
default_category: programming
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
font_awesome_icons:
  svg: font-awesome/fontawesome-webfont.svg
  yml: font-awesome/fontawesome-icons.yml

sitemap:
  path: sitemap.xml

## Themes: https://hexo.io/themes/
theme: maupassant

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
