fancybox: false ## If you want to use fancybox please set the value to true.
disqus: vadimmacagon ## Your disqus_shortname, e.g. username
google_search: true ## Use Google search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: false ## If you want to use the share button please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

## Defines the top-right navigation menu/tabs.
## Each tab can have an optional `icon` (identified by a FontAwesome class). 
menu:
  - page: blog
    directory: .
  - page: projects
    directory: projects/
  - page: about
    directory: about/
  - page: archive
    directory: archives/
  ##- page: timeline
  ##  directory: timeline/
  ##- page: rss
  ##  directory: atom.xml
  ##  icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, recent_comments and links.
  - search
  - tag
  - recent_posts
  - links

links:
  - title: My Twitter Profile
    text: macagonator
    icon: fa-twitter
    url: http://twitter.com/macagonator
  - title: My GitHub Profile 
    text: enlight
    icon: fa-github
    url: https://github.com/enlight
  - title: My BitBucket Profile 
    text: enlight
    icon: fa-bitbucket
    url: https://bitbucket.org/enlight

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Sub-directories containing static files
js: js
css: css

# Theme version
version: 0.0.0
